### ISSUE TITLE
Cannot connect to mysql in docker

### ISSUE THREAD

**Issue by xhallix** [blackbeam/rust-mysql-simple#120]
Not sure if I'm on the right track with this issue.
I've setted up my db in a docker container.

That's what the config looks like
```
version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: foobar
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
    - "3306:3306"
```

I'm not trying to establish a connection

```rust
   fn get_opts() -> Opts {
        let user = "root";
        let addr = "127.0.0.1";
        let pwd: String = String::from("1234");
        let port: u16 = 3306;
        let mut builder = OptsBuilder::default();
        builder.user(Some(user))
                .pass(Some(pwd))
                .ip_or_hostname(Some(addr))
                .tcp_port(port);      
        builder.into()
    }
    
    fn get_connection() {
      let opts = self.get_opts();
      let pool = Pool::new_manual(1, 1, opts).unwrap();
    }
```

Now I'm getting:
```error: Could not connect to address `/var/run/mysqld/mysqld.sock': No such file or directory (os error 2) ```

I debug it and in `conn/mod.rs` I saw `fn can_improved()` which improves the connection by choosing `socket` over `tcp` if possible.

I have limited knowledge in this field - so I'm not sure if this is an issue with this lib or my setup.
