### ISSUE TITLE
 Value: CodecError {Packets out of sync} appears under macos

### ISSUE THREAD

**Issue by messagebox-link** [blackbeam/rust-mysql-simple#278]
Simple code:
`let url = "mysql://link_test:password@127.0.0.1:3306/s_test";

  let pool = Pool::new(url).unwrap();
  
  let mut conn = pool.get_conn().unwrap();
`

Error message:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CodecError { Packets out of sync }'

Is there a way to develop and test under Macos?

**Comment by blackbeam** [comment]
Hi. Could you please try this on the `v21.0.0-release` branch (add the following to your `Cargo.toml`):

```toml
[patch.crates-io]
mysql = { git = 'https://github.com/blackbeam/rust-mysql-simple.git', branch = 'v21.0.0-release' }
```
