### ISSUE TITLE
Unknown authentication protocol: `mysql_clear_password` 

### ISSUE THREAD

**Issue by linusheinz** [blackbeam/rust-mysql-simple#344]
Hi there,

I am trying to retrieve data from a mysql server with r2d2  . The server requires [Client-Side Cleartext Pluggable Authentication](https://dev.mysql.com/doc/refman/5.7/en/cleartext-pluggable-authentication.html) 

But I get 

DriverError { Unknown authentication protocol: `mysql_clear_password` }

Is this a missing plugin in the driver ?

Best Linus

**Comment by blackbeam** [comment]
@linusheinz, hi!

Could you please try [this branch](https://github.com/blackbeam/rust-mysql-simple/tree/cleartext-password)?

The following should do the job:

In your Cargo.toml:

```toml
[patch.crates-io]
mysql = { git = "https://github.com/blackbeam/rust-mysql-simple", branch = "cleartext-password" }
```

Within your code:

```rust
// ...

// Enable mysql_clear_password via OptsBuilder
let opts = opts_builder.enable_cleartext_password(true);

// or alternatively enable mysql_clear_password via connection URL
let opts = Opts::from_url("mysql://shome_host/some_db?enable_cleartext_plugin=true")?;

// ...
```
